### PR TITLE
Accessibility branch

### PR DESCRIPTION
**Pull request by tsheporamantso**
**In this project I've implemented the following:-**

- [ ] Page Title - Changed page title to describe the content of the page.
- [ ] Image text alternative - Add text alternative on all image tags.
- [ ] Text Headings - No issues found.
- [ ] Color Contrast - No issues found.
- [ ] Resize - No issues found.
- [ ] Interaction - No issues found.
- [ ] Moving content - Add hover effect on the desktop navigation bar.
- [ ] Multimedia - Add hover effect on images.
- [ ] The basic structure of the page - No issues found.

### CODE REVIEW

**Review by Alfredbis29 — COMMENTED** [review]
Hi @tsheporamantso , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a wrong link for this project since I can't see request changes from the previous review , kindly submit the right PR where you have request changes , this will help the current reviewer to know what have changes so far :wink:  :wink: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by tsheporamantso** [comment]
Good day Alfred
Trust you are well. 

I kindly plea for clarity on your recommendation as there is no other code reviewer who has reviewed this PR, except you! 
I would assume you are referring to the first two commit messages that you see, and those refer to the peer-to-peer code review exercise I had with my morning team, I don't know how they got there. Thus I humble myself and plea for further clarity on PR rejection.

Kind regards,
Gladwin Tshepo Ramantso.

**Comment by Alfredbis29** [comment]
Hey I received your project as Re-review project and I can’t see where
other reviews changes so I invalidate it . You can resubmit it again please
it doesn’t affect your attempt please. Thanks

**Comment by tsheporamantso** [comment]
I think there is a glitch on the dashboard because that was my first submission.  not a Re-review and out of 3 attempt I see not I am only left with one submission. Which doesn't make sense because I only submitted once!
There is this reviewer "Eric Tuyishimire" that shows on my submission and He has never reviewed this PR and his comments are not showing on my PR.
________________________________

**Comment by Alfredbis29** [comment]
If I saw it as the first attempt and all is good why invalided it , I
judged what I saw . Maybe but I get it as second attempt

**Comment by Alfredbis29** [comment]
Ooh really I invalidate your project on my dashboard as well which means
nothing affected your attempts , so what happened then ??

**Comment by tsheporamantso** [comment]
I am as confused as you are! since you've invalidated it my attempts were not supposed to count. and furthermore, that other reviewer by the name of Eric hasn't reviewed that PR nor have I received any of his recommendations!
________________________________

**Comment by Alfredbis29** [comment]
let me try to report this to my senior and see if they will help and back to you , who is Eric ?

**Comment by Alfredbis29** [comment]
Why do u marged this ????????

**Comment by Alfredbis29** [comment]
why you do that ????????? @tsheporamantso

**Comment by Alfredbis29** [comment]
I'm trying to help you but you merged the PR

**Comment by tsheporamantso** [comment]
The status on the dashboard shows as submit! I thought you've resolved the issue? Reviewer by the name Favor has reviewed it.

**Comment by Alfredbis29** [comment]
why ???

**Comment by tsheporamantso** [comment]
________________________________

**Comment by Alfredbis29** [comment]
is there someone who approved your project ??????

**Comment by tsheporamantso** [comment]
Yes, it was approved and I assumed you've sorted the issue out since you said you'll escalate the issue!
________________________________

**Comment by Alfredbis29** [comment]
who approved it then ?

**Pull request merged**
